import json
import xml.etree.ElementTree as ET

from bpmn_assistant.config import logger
from bpmn_assistant.services.bpmn_process_transformer import BpmnProcessTransformer
from bpmn_assistant.services.pools import has_pools
from bpmn_assistant.services.validate_bpmn import validate_bpmn, validate_pools
from bpmn_assistant.services.element_details import ARTIFACT_TYPES, write_artifacts, write_event_details, write_loop


class BpmnXmlGenerator:
    """
    Class to generate BPMN XML from the BPMN process data in JSON format.
    """

    def __init__(self):
        self.transformer = BpmnProcessTransformer()

    def create_bpmn_xml(self, process: list[dict]) -> str:
        """
        Create BPMN XML from the process data.
        Args:
            process: BPMN process structure generated by the LLM.
            The BPMN XML string.
        """

        if has_pools(process):
            validate_pools(process)
            return self._create_pools_xml(process)
        if process:
            validate_bpmn(process)
        self._subprocess_expansion = {}
        transformed_process = self.transformer.transform(process)
        logger.debug(
            f"Transformed process:\n{json.dumps(transformed_process, indent=2)}"
        )

        # Create the root element (definitions)
        root = ET.Element("definitions")
        root.set("xmlns", "http://www.omg.org/spec/BPMN/20100524/MODEL")
        root.set("xmlns:bpmndi", "http://www.omg.org/spec/BPMN/20100524/DI")
        root.set("xmlns:dc", "http://www.omg.org/spec/DD/20100524/DC")
        root.set("xmlns:di", "http://www.omg.org/spec/DD/20100524/DI")
        root.set("id", "definitions_1")

        # Create the process element
        process_element = ET.SubElement(root, "process")
        process_element.set("id", "Process_1")
        process_element.set("isExecutable", "false")

        self._write_scope(process_element, process, root)
        self._write_subprocess_di(root)
        return ET.tostring(root, encoding="unicode")

    def _write_scope(self, process_element, process, root):
        transformed_process = self.transformer.transform(process)

        # Add elements
        for element in transformed_process["elements"]:
            elem = ET.SubElement(process_element, element["type"])
            elem.set("id", element["id"])

            # Add label if it exists
            if element["label"]:
                elem.set("name", element["label"])
            if element['type'] == 'boundaryEvent':
                elem.set('attachedToRef', element['attached_to'])
                elem.set('cancelActivity', str(element['cancel_activity']).lower())

            # Add default flow attribute for inclusive/exclusive gateways if it exists
            if "default_flow" in element and element["default_flow"]:
                elem.set("default", element["default_flow"])

            # Add incoming and outgoing flows as child elements
            for incoming in element["incoming"]:
                ET.SubElement(elem, "incoming").text = incoming
            for outgoing in element["outgoing"]:
                ET.SubElement(elem, "outgoing").text = outgoing

            # Add event definition if it exists
            if "eventDefinition" in element and element["eventDefinition"]:
                event_def_type = element["eventDefinition"]
                # Create event definition element with a unique ID
                event_def_elem = ET.SubElement(elem, event_def_type)
                event_def_elem.set("id", f"{event_def_type}_{element['id']}")
                write_event_details(event_def_elem, element, root)
            if element.get('loop'):
                write_loop(elem, element['loop'])
            if element['type'] == 'subProcess':
                self._subprocess_expansion[element['id']] = element['expanded']
                self._write_scope(elem, element['process'], root)

        # Add flows
        for flow in transformed_process["flows"]:
            seq_flow = ET.SubElement(process_element, "sequenceFlow")
            seq_flow.set("id", flow["id"])
            seq_flow.set("sourceRef", flow["sourceRef"])
            seq_flow.set("targetRef", flow["targetRef"])

            # Add condition if it exists
            if flow["condition"]:
                seq_flow.set("name", flow["condition"])

        write_artifacts(process_element, process)

    def _write_subprocess_di(self, root, plane_id='Process_1'):
        # DI carries expanded/collapsed presentation. The layout service replaces
        # these seed bounds while preserving expansion and subprocess contents.
        subprocesses = getattr(self, '_subprocess_expansion', {})
        if not subprocesses:
            return
        di = '{http://www.omg.org/spec/BPMN/20100524/DI}'
        dc = '{http://www.omg.org/spec/DD/20100524/DC}'
        used_ids = {element.get('id') for element in root.iter()}

        def unique_id(base):
            candidate = base
            while candidate in used_ids:
                candidate += '_di'
            used_ids.add(candidate)
            return candidate

        diagram = ET.SubElement(root, di + 'BPMNDiagram', {'id': unique_id('ActivityDiagram')})
        plane = ET.SubElement(diagram, di + 'BPMNPlane', {'id': unique_id('ActivityPlane'), 'bpmnElement': plane_id})
        for identifier, expanded in subprocesses.items():
            shape = ET.SubElement(plane, di + 'BPMNShape', {
                'id': unique_id(f'{identifier}_di'), 'bpmnElement': identifier, 'isExpanded': str(expanded).lower(),
            })
            ET.SubElement(shape, dc + 'Bounds', {'x': '0', 'y': '0', 'width': '350', 'height': '200'})

    def _create_pools_xml(self, pools: list[dict]) -> str:
        artifacts = [item for item in pools if item['type'] in ARTIFACT_TYPES]
        pools = [item for item in pools if item['type'] == 'pool']
        namespace = 'http://www.omg.org/spec/BPMN/20100524/MODEL'
        ET.register_namespace('', namespace)
        def tag(name):
            return f'{{{namespace}}}{name}'
        root = ET.Element(tag('definitions'), {
            'id': 'definitions_1', 'targetNamespace': 'https://bpmn-assistant.local/processes',
        })
        collaboration = ET.SubElement(root, tag('collaboration'), {'id': 'Collaboration_1'})
        expansions = {}
        for pool in pools:
            ET.SubElement(collaboration, tag('participant'), {
                'id': pool['id'], 'name': pool['label'], 'processRef': pool['process_id'],
            })
            process_xml = ET.fromstring(self.create_bpmn_xml(pool['process']))
            expansions.update(self._subprocess_expansion)
            process_element = process_xml.find(tag('process'))
            process_element.set('id', pool['process_id'])
            if pool.get('lanes'):
                lane_set = ET.Element(tag('laneSet'), {'id': f"{pool['process_id']}_lanes"})
                nodes = self.transformer.transform(pool['process'])['elements']
                for lane in pool['lanes']:
                    lane_element = ET.SubElement(lane_set, tag('lane'), {'id': lane['id'], 'name': lane['label']})
                    for node in nodes:
                        if node.get('lane_id') == lane['id']:
                            ET.SubElement(lane_element, tag('flowNodeRef')).text = node['id']
                process_element.insert(0, lane_set)
            root.append(process_element)
            for definition in process_xml:
                if definition.tag.split('}')[-1] not in ('process', 'BPMNDiagram') and not any(
                    child.get('id') == definition.get('id') for child in root
                ):
                    root.append(definition)
        for pool in pools:
            for flow in pool.get('message_flows', []):
                attributes = {
                    'id': flow['id'], 'sourceRef': flow['source_ref'],
                    'targetRef': flow['target_ref'],
                }
                if flow.get('label'):
                    attributes['name'] = flow['label']
                ET.SubElement(collaboration, tag('messageFlow'), attributes)
        write_artifacts(collaboration, artifacts)
        self._subprocess_expansion = expansions
        self._write_subprocess_di(root, 'Collaboration_1')
        return ET.tostring(root, encoding='unicode')
