import json
import xml.etree.ElementTree as ET

from bpmn_assistant.config import logger
from bpmn_assistant.services.bpmn_process_transformer import BpmnProcessTransformer
from bpmn_assistant.services.pools import has_pools
from bpmn_assistant.services.validate_bpmn import validate_pools


class BpmnXmlGenerator:
    """
    Class to generate BPMN XML from the BPMN process data in JSON format.
    """

    def __init__(self):
        self.transformer = BpmnProcessTransformer()

    def create_bpmn_xml(self, process: list[dict]) -> str:
        """
        Create BPMN XML from the process data.
        Args:
            process: BPMN process structure generated by the LLM.
            The BPMN XML string.
        """

        if has_pools(process):
            validate_pools(process)
            return self._create_pools_xml(process)
        transformed_process = self.transformer.transform(process)
        logger.debug(
            f"Transformed process:\n{json.dumps(transformed_process, indent=2)}"
        )

        # Create the root element (definitions)
        root = ET.Element("definitions")
        root.set("xmlns", "http://www.omg.org/spec/BPMN/20100524/MODEL")
        root.set("xmlns:bpmndi", "http://www.omg.org/spec/BPMN/20100524/DI")
        root.set("xmlns:dc", "http://www.omg.org/spec/DD/20100524/DC")
        root.set("xmlns:di", "http://www.omg.org/spec/DD/20100524/DI")
        root.set("id", "definitions_1")

        # Create the process element
        process_element = ET.SubElement(root, "process")
        process_element.set("id", "Process_1")
        process_element.set("isExecutable", "false")

        # Add elements
        for element in transformed_process["elements"]:
            elem = ET.SubElement(process_element, element["type"])
            elem.set("id", element["id"])

            # Add label if it exists
            if element["label"]:
                elem.set("name", element["label"])

            # Add default flow attribute for inclusive/exclusive gateways if it exists
            if "default_flow" in element and element["default_flow"]:
                elem.set("default", element["default_flow"])

            # Add incoming and outgoing flows as child elements
            for incoming in element["incoming"]:
                ET.SubElement(elem, "incoming").text = incoming
            for outgoing in element["outgoing"]:
                ET.SubElement(elem, "outgoing").text = outgoing

            # Add event definition if it exists
            if "eventDefinition" in element and element["eventDefinition"]:
                event_def_type = element["eventDefinition"]
                # Create event definition element with a unique ID
                event_def_elem = ET.SubElement(elem, event_def_type)
                event_def_elem.set("id", f"{event_def_type}_{element['id']}")

        # Add flows
        for flow in transformed_process["flows"]:
            seq_flow = ET.SubElement(process_element, "sequenceFlow")
            seq_flow.set("id", flow["id"])
            seq_flow.set("sourceRef", flow["sourceRef"])
            seq_flow.set("targetRef", flow["targetRef"])

            # Add condition if it exists
            if flow["condition"]:
                seq_flow.set("name", flow["condition"])

        xml_string = ET.tostring(root, encoding="unicode")

        return xml_string

    def _create_pools_xml(self, pools: list[dict]) -> str:
        namespace = 'http://www.omg.org/spec/BPMN/20100524/MODEL'
        ET.register_namespace('', namespace)
        def tag(name):
            return f'{{{namespace}}}{name}'
        root = ET.Element(tag('definitions'), {
            'id': 'definitions_1', 'targetNamespace': 'https://bpmn-assistant.local/processes',
        })
        collaboration = ET.SubElement(root, tag('collaboration'), {'id': 'Collaboration_1'})
        for pool in pools:
            ET.SubElement(collaboration, tag('participant'), {
                'id': pool['id'], 'name': pool['label'], 'processRef': pool['process_id'],
            })
            process_xml = ET.fromstring(self.create_bpmn_xml(pool['process']))
            process_element = process_xml.find(tag('process'))
            process_element.set('id', pool['process_id'])
            if pool.get('lanes'):
                lane_set = ET.Element(tag('laneSet'), {'id': f"{pool['process_id']}_lanes"})
                nodes = self.transformer.transform(pool['process'])['elements']
                for lane in pool['lanes']:
                    lane_element = ET.SubElement(lane_set, tag('lane'), {'id': lane['id'], 'name': lane['label']})
                    for node in nodes:
                        if node.get('lane_id') == lane['id']:
                            ET.SubElement(lane_element, tag('flowNodeRef')).text = node['id']
                process_element.insert(0, lane_set)
            root.append(process_element)
        return ET.tostring(root, encoding='unicode')
