from typing import Optional


class BpmnProcessTransformer:
    """
    Class to transform the BPMN process structure generated by the LLM into a new structure more suitable for BPMN XML generation.
    """

    def transform(self, process: list[dict]) -> dict:
        """
        Restructure the original BPMN JSON structure into a new structure more suitable for BPMN XML generation.

        Example output structure::

            {
                "elements": [
                    {
                        "id": "element_id",
                        "type": "element_type",
                        "label": "element_label",
                        "incoming": ["incoming_flow_id"],
                        "outgoing": ["outgoing_flow_id"]
                    }
                ],
                "flows": [
                    {
                        "id": "flow_id",
                        "sourceRef": "source_element_id",
                        "targetRef": "target_element_id",
                        "condition": "flow_condition"
                    }
                ]
            }
        """

        elements = []
        flows = []

        def handle_exclusive_gateway(
            element: dict, next_element_id: Optional[str] = None
        ):
            for branch in element["branches"]:
                branch_structure = self.transform(branch["path"])
                elements.extend(branch_structure["elements"])
                flows.extend(branch_structure["flows"])

                # Add the flow from the exclusive gateway to the first element in the branch (if the branch
                # is not empty)
                first_element = (
                    branch_structure["elements"][0]
                    if branch_structure["elements"]
                    else None
                )
                if first_element:
                    flows.append(
                        {
                            "id": f"{element['id']}-{first_element['id']}",
                            "sourceRef": element["id"],
                            "targetRef": first_element["id"],
                            "condition": branch["condition"],
                        }
                    )

                last_element = (
                    branch_structure["elements"][-1]
                    if branch_structure["elements"]
                    else None
                )
                next_id = (
                    branch.get("next") or next_element_id
                )  # Use the 'next' attribute if it exists, otherwise use the next element ID

                # If the branch is not empty and there is a next element, connect the last element
                # of the branch and the next element
                if last_element and next_id:
                    flows.append(
                        {
                            "id": f"{last_element['id']}-{next_id}",
                            "sourceRef": last_element["id"],
                            "targetRef": next_id,
                            "condition": None,
                        }
                    )

            # If the exclusive gateway has a 'join' gateway, add it to the elements list
            if element.get("has_join", False):
                join_gateway_id = f"{element['id']}-join"
                elements.append(
                    {
                        "id": join_gateway_id,
                        "type": "exclusiveGateway",
                        "label": None,
                    }
                )
                return join_gateway_id

            return None

        def handle_parallel_gateway(element: dict):
            # Create a 'join' parallel gateway element
            join_gateway_id = f"{element['id']}-join"
            elements.append(
                {
                    "id": join_gateway_id,
                    "type": "parallelGateway",
                    "label": None,
                }
            )

            for branch in element["branches"]:
                branch_structure = self.transform(branch)
                elements.extend(branch_structure["elements"])
                flows.extend(branch_structure["flows"])

                # Add the flow from the parallel gateway to the first element in the branch
                first_element = branch_structure["elements"][0]
                flows.append(
                    {
                        "id": f"{element['id']}-{first_element['id']}",
                        "sourceRef": element["id"],
                        "targetRef": first_element["id"],
                        "condition": None,
                    }
                )

                # Add the flow from the last element in the branch to the join gateway
                last_element = branch_structure["elements"][-1]
                flows.append(
                    {
                        "id": f"{last_element['id']}-{join_gateway_id}",
                        "sourceRef": last_element["id"],
                        "targetRef": join_gateway_id,
                        "condition": None,
                    }
                )

            return join_gateway_id

        for index, element in enumerate(process):
            next_element_id = (
                process[index + 1]["id"] if index < len(process) - 1 else None
            )

            elements.append(
                {
                    "id": element["id"],
                    "type": element["type"],
                    "label": element.get("label", None),
                }
            )

            if element["type"] == "exclusiveGateway":
                join_gateway_id = handle_exclusive_gateway(element, next_element_id)

                # Connect the join gateway to the next element in the process
                if join_gateway_id and next_element_id:
                    flows.append(
                        {
                            "id": f"{join_gateway_id}-{next_element_id}",
                            "sourceRef": join_gateway_id,
                            "targetRef": next_element_id,
                            "condition": None,
                        }
                    )
            elif element["type"] == "parallelGateway":
                join_gateway_id = handle_parallel_gateway(element)

                # Connect the join gateway to the next element in the process
                if index < len(process) - 1:
                    flows.append(
                        {
                            "id": f"{join_gateway_id}-{process[index + 1]['id']}",
                            "sourceRef": join_gateway_id,
                            "targetRef": process[index + 1]["id"],
                            "condition": None,
                        }
                    )
            else:
                # Add the flow between the current element and the next element in the process
                if index < len(process) - 1:
                    flows.append(
                        {
                            "id": f"{element['id']}-{process[index + 1]['id']}",
                            "sourceRef": element["id"],
                            "targetRef": process[index + 1]["id"],
                            "condition": None,
                        }
                    )

        # Loop through the elements and flows to find the incoming and outgoing flows
        for element in elements:
            element["incoming"] = [
                flow["id"] for flow in flows if flow["targetRef"] == element["id"]
            ]
            element["outgoing"] = [
                flow["id"] for flow in flows if flow["sourceRef"] == element["id"]
            ]

        return {"elements": elements, "flows": flows}
